sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-083
env:
  global:
    -
      # LTD_AWS_ID
      secure: l7+KVT2Aqozz0qXPSoBzB+lGNBYT+2c1YlE3hFfq5Jwt/X9LFH1lJGpwK+ioKngCGDwv03Tl+oBNFA2+J2lUjqDG2sZWXcp4hBXfnvS4OA24Xq2JJvOq3/BneqZ+b7p0AWZ01b2TrZNHrKy+Og4tDksrg/+3k5Q5cfvrQBUjAGWrVuvOSto8awfU1qTIDHXT/36bKGr5Y7vTasGfx1qTFoIS+QdAn6+zFqDGsLdQPImET/6EeBmGZOcI3rhdul+QrMUxGEAct9ND22VWptOwLnilIWP84NfKGHO3pEw1szzAT3gbhm1QFTVCxqF5jHO13cmzhExKtWYf9bIR9PXwEfkYDMIlobbAvOpGMcvBfNzyH9vBOtdB0XpfgWvBNSHb8qVMJQy6FK5uezPvlnr+u1M01ewJ4hAJizAjBiXY2UwzFRuJeYV9dqE8CekpBNodQMuHGS2lxrP/67WvVxNEDP9QYihpv5xgJlxHUkQrE2LnRUQmMOgNvglcBevX/w579YQglLk2iGmb6m9HC6rd1TecrsB8D/Ry+LJDS+V/RQIe39dH66VmnHQQp2r8xisFBLKXibS0lVPVU5i5KJpnCF/OP18BfBNGm3WHOIGO7wZSyX3Gi2Ct3PEzFvXhcrac8MMy0gww8Ooaln61+r6wVX9g91q25iu8x9WsqtJF2wA=
    -
      # LTD_AWS_SECRET
      secure: WKnPE3yFcbuSphZgamiqtggr5MrjpCMR38YQ4uz5NqyoidY0yYAxWTXziqSK9X8vxPunXmEDHrxgQ7QtSed2QIGwe1aapME1o8wA+DizjM5GNDwTHzzs7kmUQoX2FTAmvaKo8d32KQNPpEyW/i+8Hqs7mCyL2N5GXXRyEgUQSSCNYk7076+keXnSNExWP9NryyyY7x4qBP/fqDrlzGcz+ixSqnhlmn6jw4rAWsj+jtBUT9coj9FYnBcNJL5DviYXskQoawOM5QToVn2Au/zjt11qf/uwm4LL2a+uAGsaHy33ipF9qsieN/9+WNDV0WqEqcXI9sDBYinvXRwNNNzS6hB+cD/Sv0Aw7Oq0PhxKHdQomxQP4RNkumiwXnEeNC7fDqi7rzxVANQbjg0ZtTWE3nASwfVcl/CkWj4MmerbX6nNAsFDNE7q2+HwxOjmLMUOOF9mF3lF8O09J8Gsx1++fuGy4BOojQDQT00H2UFIwxIn/hahYuS97oCTXf6w6WmyeB9cblrAS3W5bKbHjm29RYXi4S0WrekzN2dbggSbutO0YkoNwu70wR2b6KFl6sv5OvDwylkg9uE3BeAyIj+kwaFlo9QTfk7kPwEG2NK6Xi1Iq+nfxjWxH8gU88ccGpHz1OgT3GFb6Z51iD9HZzKGRJ98imcAFOXdHEqWIpQDQHA=
    -
      # LTD_USERNAME
      secure: sG6/yM8U/Em+7PQJSJ5ONozRIEQyZLwpjMO2TduwYZH7OmMO2QYdpPOZKUSYqj+Hye7dANoDm3d8NCoxPSzc3GHnJMTW32WRQhylyx/zH9eIh6i0anTOncB5fSJ96nvAdHK6LFqFAjiK6tjNNbEzfvPBAE6dnAm6Gp1zN1nnPCZTq2heU01QiwCH8E6NFzPyq0fqDj2arBQjfCWm40IJyoC3pH6703XV2TTTcH1mXsKE/qYoxzSq/c4/kCBGZKKVx76C+MFVJknRWfc3SoTgdwA91LvDdFkop+6cHDXYoDimtUzx+gP+AHTBk3ZQCGkfpw1a41IbPxYzI4Mfr0okMMvq48/ThHl4osCTrKfyhf++QGOT9qbWbvZPThEbybRJpVt4Sbmy9pveZoDMU5hUmx9MVNu7kK065fMSABPoyOXg0oLOpGFkw8IbyzsYBYZX7X61vfHHYT9hdxdNZWIsA7yYo6r8uFeTF0Nyg6sRkmyP6LkFNoXVeh7wewHY8FKxHQrvnFcgr/hMQuMZ0IaLdZjU/waJwmwp3V0CkDTUmWBe0S40nC5wXWYVu4hRlCU7tJ/l342yr7OF0P9GFw9NWZBpoI7ZOYwucy5QNWL6ZLzHXIb4IVikcERUnMEY3GyYDmAZAYKGxS4rcKFA3XoeujHjhkuJxYCOxhTwcZDKauA=
    -
      # LTD_PASSWORD
      secure: jJP+F8x8kK8lTffOHjSwlsJj3AWw5QSAVofeAHsREB3e2CSKs/DHAlx38i6TK7pbqq8JFPYqCFbhOG8J9tjhys8QWu3ORDsKWSBhH9JxFazxc1o1t+d+RtZFJajx4fq0nVrSWou6r25T5eLvrm2n2zDZgVGLP5xJqLCs6b8lAqQyRrMUC8Ja4W7910h3VxPSD/HzUQQQZIXfDDYR3Pl9v5GdV7fqeBiiIFApj3r8vpf+GBO7PyQZj6QvuM8q+04NDtDwANi24vuwXP+R4yxzDtTPYV9Ko8HWzZN63+S6aUjk30Twp1NnNo7P9sCrrWaBYEWpXSTymGu+UWmAeZ1WKTFD9Tyd/EeF9BZ7aRDIEFaDLwN4EZWRf61GmmE35FF2hJKq0es6Y30QPLOC/entPBJkxPn11nswZYUVFectV8FHfOubmb6FGjjZ4D44EIZaUe4WM1kciLgmiZLITFyVubmWHeK6zAiKPl8L3NG2y6T7xpIRwskLp4YYOGCjY+l3NBsAxEceYok5eQPbNa2WIsRLDHE9fH7tk2udzjzhwsng2KIuC83ArqoVCIfTu4n85n/8rd3LTCODz0xSarURu/gjmH3pcn5Lj6RYb8qhG/85ga4WCeqX6Tu/CsOygxl3MZMGbB1eYCOa4URCX7i5QLApBv8oSNhd99mV0ME858o=
